meta:
  url: https://gabelluardo.github.io/plenaria-mar2022
  title: Plenaria marzo 2022
  description:
  siteName: plenaria-mar2022
slide:
  loop: false
  targetBlank: true
  ui:
    sidebar: false
    pagination: bullets
    effect:
  code:
    theme: okaidia
